version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: hangeul_school_db
    restart: always
    environment:
      MYSQL_DATABASE: hangeul_school
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql