[variables]
NIXPACKS_JDK_VERSION = "17"
NODE_ENV = "production"

[phases.install]
cmds = ["chmod +x gradlew"]

[phases.build]
cmds = ["./gradlew build -x test --no-daemon"]

[start]
cmd = "java -jar build/libs/*.jar"